### ISSUE TITLE
Chapter 2 - Page 81 - Bullet 4: dotnet ef dbcontext command doesn't like InitialDirectory

### ISSUE THREAD

**Issue by BobMolloy** [markjprice/apps-services-net7#4]
When using the dotnet ef dbcontext command as shown in the book, I get the attached screen shot complaining about initialdirectory.

I changed InitialDirectory to database and the Models were created.

![dotnet ef fail](https://user-images.githubusercontent.com/7458504/210153014-da330eb4-3aee-45a3-a417-f7cd424c2407.png)

**Comment by markjprice** [comment]
Your command failed because you used `InitialCatalog`. The correct name is `Initial Catalog`. The legacy name `database` also works but it remains for backwards compatibility with ODBC connection strings.
![image](https://user-images.githubusercontent.com/14040265/210177374-d3b8ae52-a7b6-488c-8c1d-c141672d4324.png)

**Comment by BobMolloy** [comment]
The broke between Initial and Catalog in the book. When I copied and pasted the command, I deleted the space.
