### ISSUE TITLE
Chapter 2 - Page 85 - First Bullet: DbSets not set to null-forgiving

### ISSUE THREAD

**Issue by BobMolloy** [markjprice/apps-services-net7#5]
**None** of the DbSet\<T> properties are set to the null-forgiving value in my code.

**Comment by charlygg** [comment]
I think it is because the code was generated using Entity Framework Core and the tool is not aware of the non-nullable property initialization.

A sample from the code generated by scaffolding looks like the following line

`public virtual DbSet<AlphabeticalListOfProduct> AlphabeticalListOfProducts { get; set; }`

A workaround for this issue that worked for me is to initialize each DbSet inside the DbContext class to this 

`public virtual DbSet<AlphabeticalListOfProduct> AlphabeticalListOfProducts => Set<AlphabeticalListOfProduct>();    `

I followed Microsoft's suggestion to initialize DbSet according to [this link](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#dbcontext-and-dbset ), maybe there's a better solution than changing every DbSet, it won't be a solution if we had more than 100 DbSet

After the change, I was able to continue the exercise and the code was compiled and executed with no errors.

![image](https://user-images.githubusercontent.com/8092680/210191138-e37539c0-744b-427b-8a5c-5ecb63c54c15.png)

I hope it could be helpful

**Comment by markjprice** [comment]
The `dotnet-ef` tool team must have made some template changes after I wrote that chapter. The easiest thing to do is to disable the null checks in the `NorthwindDb.cs` class file. I have created errata items about this:
https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/errata.md#page-82---defining-the-northwind-database-model

**Comment by BobMolloy** [comment]
Sure, it’s easy enough to fix. Select the lines, do a change-all on the } to “} = null!;”.
